version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pet_database
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    image: pet-app:latest
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pet_database?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    volumes:
      - /home/ubuntu/pet_uploads/products:/public/products
      - /home/ubuntu/pet_uploads/images:/public/images
      - /home/ubuntu/pet_uploads/avatar:/public/avatar
      - /home/ubuntu/pet_uploads/certificates:/public/certificates/
      - /home/ubuntu/pet_uploads/defaultAvatar:/public/defaultAvatar
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  db-data:
    driver: local


networks:
  mynetwork:
