export const UPDATE_POST_LIKE = "UPDATE_POST_LIKE";
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const SET_POSTS = 'SET_POSTS';
export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = "REMOVE_LIKE";
export const LIKE_STATUS = 'LIKE_STATUS';


export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

